version: '3.8'

services:
  ubuntu-novnc:
    image: sickcodes/docker-ubuntu-vnc:latest
    container_name: ubuntu24-vm
    privileged: true
    environment:
      - RAM=4096
      - CPU=4
    ports:
      - "8006:8080"        # noVNC access via web browser
    volumes:
      - ./iso:/iso
      - ./disk:/disk
    command: >
      bash -c "
        qemu-img create -f qcow2 /disk/ubuntu24.qcow2 40G &&
        qemu-system-x86_64 \
          -enable-kvm \
          -m 4096 \
          -smp 4 \
          -boot d \
          -cdrom /iso/ubuntu-24.04-desktop-amd64.iso \
          -hda /disk/ubuntu24.qcow2 \
          -vnc :0 \
          -net nic \
          -net user &
        /noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 8080
      "
